version: '3.4'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: thuchanh
      MYSQL_USER: root
      # MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - my-net

  be:
    image: be
    ports:
      - 8888:8888
    depends_on:
      - db
    networks:
      - my-net
      
  fe:
    image: fe-app
    ports:
      - 8080:8080
    depends_on:
      - be

volumes:
  database:
    driver: local
networks:
  my-net:
    driver: bridge